language: node_js
node_js:
- 8.9.4
cache:
  directories:
    - $HOME/.npm
branches:
  only:
  - master
  - dev
install:
  - npm i -g npm@5.7.1
  - npm ci
before_script:
- npm install -g ionic cordova jest
notifications:
  webhooks:
    urls:
    - https://hooks.glip.com/webhook/6d688e2d-f076-4521-8213-f2479e99afe6
    on_success: never
    on_failure: always
    on_start: never
script:
- npm run test-ci
deploy:
  provider: heroku
  api_key: $HEROKU_KEY
  app: ssf-reboot
  on:
    repo: SoftStackFactory/reboot
